INSERT INTO insects (common_name, species) VALUES 
("African black beetle", "Heteronychus arator"),
("Amnemus weevil", "Amnemus sp."),
("Ants, Seed harvesting", "Pheidole"),
("Aphids", "various"),
("Aphid, Bluegreen", "Acyrthosiphon kondoi"),
("Aphid, Cabbage", "Brevicoryne brassicae"),
("Aphid, Corn", "Rhopalosiphum maidis"),
("Aphid, Cotton", "Aphis gossypii"),
("Aphid, Cowpea", "Aphis craccivora"),
("Aphid, Green peach", "Myzus persicae"),
("Aphid, Oat", "Rhopalosiphum padi"),
("Aphid, Pea", "Acyrthosiphon pisum"),
("Aphid, Rice root", "Rhopalosiphum rufiabdominalis"),
("Aphid, Rose grain", "Metopolophium dirhodum"),
("Aphid, Soybean", "Aphis glycine"),
("Aphid, Spotted alfalfa", "Therioaphis trifolii"),
("Aphid, Turnip", "Lipaphis erysimi"),
("Aphid, Wheat", "Rhopalosiphum padi"),
("Armyworms", "various"),
("Armyworm, Common", "Leucania convecta"),
("Armyworm, Dayfeeding", "Spodoptera exempta"),
("Armyworm, Lawn", "Spodoptera mauritia"),
("Armyworm, Lesser", "Spodoptera exigua"),
("Armyworm, Northern", "Mythimna separata"),
("Armyworm, Sugarcane", "Leucania stenographa"),
("Australian plague locust", "Chortoicetes terminifera"),
("Bean fly", "Ophiomyia phaseoli"),
("Bean leafroller", "Omiodes diemenalis"),
("Bean looper or Mocis", "Mocis alterna"),
("Bean podborer", "Maruca vitrata"),
("Bean spider mite", "Tetranychus ludeni"),
("Beet webworm", "Spoladea recurvalis"),
("Black field cricket", "Teleogryllus commodus, T. oceanicus, Lepidogryllus parvulus"),
("Black field earwig", "Nala lividipes"),
("Black leaf beetle", "Rhyparida nitida"),
("Black sunflower scarab", "Pseudoheteronyxsp."),
("Bluegreen aphid", "Acyrthosiphon kondoi"),
("Blue oat mite", "Penthaleus major"),
("Brown bean bug, Large", "Riptortus serripes"),
("Brown bean bug, Small", "Melanacanthus scutellaris"),
("Brown flea beetle", "Chaetocnemasp."),
("Brown mirid", "Creontiades pacificus"),
("Brown pasture looper", "Ciampa arietaria"),
("Brown shield bug", "Dictyotus caenosus"),
("Brown wheat mite", "Petrobia latens"),
("Bruchid, Cowpea", "Callosobruchus maculatus"),
("Cabbage aphid", "Brevicoryne brassicae"),
("Cabbage moth", "Plutella xylostella"),
("Castor oil looper", "Achaea janata"),
("Click beetle", "Agrypnusspp."),
("Clover springtail", "Sminthurus viridis"),
("Cluster caterpillar", "Spodoptera litura"),
("Cockroach, Wingless", "Calolampraspp."),
("Common armyworm", "Leucania convecta"),
("Common grass blue butterfly", "Zizina labradus"),
("Corn aphid", "Rhopalosiphum maidis"),
("Corn earworm", "Helicoverpa armigera"),
("Cotton aphid", "Aphis gossypii"),
("Cotton bollworm", "Helicoverpa armigera"),
("Cotton harlequin bug", "Tectocoris diophthalmus"),
("Cotton leafhopper", "Amrasca terraereginae"),
("Cotton leafperforator", "Bucculatrix gossypii"),
("Cotton looper", "Anomis flava"),
("Cottonseed bug", "Oxycarenus luctuosus"),
("Cotton seedling thrip", "Thrips tabaci"),
("Cotton tipworm", "Crocidosema plebejana"),
("Cotton webspinner", "Achyra affinitalis"),
("Cowpea aphid", "Aphis craccivora"),
("Cowpea bruchid", "Callosobruchus maculatus"),
("Cricket, Black field", "Teleogryllus commodus, T. oceanicus, Lepidogryllus parvulus"),
("Crop mirid", "Sidnia kinbergi"),
("Cutworm", "Agrotisspp."),
("Dayfeeding armyworm", "Spodoptera exempta"),
("Diamondback moth", "Plutella xylostella"),
("Dried fruit beetle", "Carpophilusspp."),
("Eastern false wireworm", "Pterohelaeusspp."),
("Earwig, Black field", "Nala lividipes"),
("Etiella moth", "Etiella behrii"),
("False wireworm", "PterohelaeusandGonocephalumspp."),
("Flea beetles, Brown and Redheaded", "ChaetocnemaandNisostrasp."),
("Flower beetle", "Carpophilusspp."),
("Grasshoppers and locusts", "various"),
("Grasshopper, Wingless", "Phaulacridium vittatum"),
("Greenhouse whitefly", "Trialeurodes vaporariorum"),
("Green peach aphid", "Myzus persicae"),
("Green mirid", "Creontiades dilutus"),
("Green vegetable bug", "Nezara viridula"),
("Green stink bug", "Plautia affinis"),
("Grey cluster bug", "Nysius clevelandensis"),
("Helicoverpaspecies ", "armigera, punctigera"),
("Jassids ", "leafhoppers"),
("Lawn armyworm", "Spodoptera mauritia"),
("Leafhoppers ", "jassids"),
("Leafhopper, cotton", "Amrasca terraereginae"),
("Leafhopper, lucerne", "Austroasca alfalfae"),
("Leafhopper, maize", "Cicadulina bimaculata"),
("Leafhopper, vegetable", "Austroasca viridigrisea"),
("Legume webspinner", "Omiodes diemenalis"),
("Lesser armyworm", "Spodoptera exigua"),
("Light brown apple moth", "Epiphyas postvittana"),
("Locust, Australian plague", "Chortoicetes terminifera"),
("Locust, Migratory", "Locusta migratoria"),
("Locust, Yellow-winged", "Gastrimargus musicus"),
("Locust, Spur-throated", "Austracris "),
("Loopers", "various"),
("Looper, Bean or Mocis", "Mocis alterna"),
("Looper, Brown pasture", "Ciampa arietaria"),
("Looper, Castor oil", "Achaea janata"),
("Looper, Cotton", "Anomis flava"),
("Looper, Sugarcane", "Mocis frugalis"),
("Looper, Soybean", "Thysanoplusia orichalcea"),
("Looper, Tobacco", "Chrysodeixis argentifera"),
("Looper, Vegetable", "Chrysodeixis eriosoma"),
("Mocis trifasciata", ""),
("Pantydia spp.", ""),
("Lucerne crownborer", "Zygrita diva"),
("Lucerne flea", "Sminthurus viridis"),
("Lucerne leafhopper", "Austroasca alfalfae"),
("Lucerne leafroller", "Merophyas divulsana"),
("Lucerne seed wasp", "Bruchophagus roddi"),
("Lucerne seed web moth", "Etiella behrii"),
("Maize leafhopper", "Cicadulina bimaculata"),
("Maize thrips", "Frankliniella williamsi"),
("Mealybug", "Family Psuedococcidae"),
("Mealybug, solenopsis", "Phenacoccus solenopsis"),
("Midge, Sorghum", "Stenodiplosis sorghicola"),
("Migratory locust", "Locusta migratoria"),
("Mirids", "CreontiadesandSidniaspp."),
("Mites", "various"),
("Mite, Bean spider", "Tetranychus ludeni"),
("Mite, Brown wheat", "Petrobia latens"),
("Mite, Blue oat", "Penthaleus major"),
("Mite, Peanut", "Paraplonobiaspp."),
("Mite, Redlegged earth", "Halotydeus destructor"),
("Mite, Strawberry spider", "Tetranychus lambi"),
("Mite, Two-spotted", "Tetranychus urticae"),
("Mocis alterna", "bean looper"),
("Mocis frugalis", "sugarcane looper"),
("Mocis trifasciata", ""),
("Monolepta ", "red-houldered leaf beetle"),
("Native budworm", "Helicoverpa punctigera"),
("Native whitefly", "Bemisia tabaci"),
("Northern armyworm", "Mythimna separata"),
("Oat aphid", "Rhopalosiphum padi"),
("Onion thrip", "Thrips tabaci"),
("Pale cotton stainer bug", "Dysdercus sidae"),
("Pantydiaspp.", ""),
("Pea aphid", "Acyrthosiphon pisum"),
("Pea blue butterfly", "Lampides boeticus"),
("Peanut mite", "Paraplonobiaspp."),
("Peanut scarab", "Heteronyxspp."),
("Pea weevil", "Bruchus pisorum"),
("Pinkspotted bollworm", "Pectinophora scutigera"),
("Plague thrip", "Thrips imaginis"),
("Podsucking bugs", "various, includingNezara viridula"),
("Redbanded shield bug", "Piezodorus oceanicus"),
("Redheaded flea beetle", "Nisotrasp."),
("Redlegged earth mite", "Halotydeus destructor"),
("Redshouldered leaf beetle", "Monolepta australis"),
("Rice root aphid", "Rhopalosiphum rufiabdominalis"),
("Rose grain aphid", "Metopolophium dirhodum"),
("Rough bollworm", "Earias huegeliana"),
("Rutherglen bug", "Nysius vinitor"),
("Seed harvesting ants", "Pheidolespp."),
("Scarab, Black sunflower", "Pseudoheteronyxsp."),
("Scarab, Peanut", ""),
("Shoot flies", "Atherigonasp."),
("Silverleaf whitefly", "Bemisia tabacibiotype B and Australian native AN"),
("Silverleaf whitefly", "Bemisia tabacibiotype Q"),
("Sitona weevil", "Sitona discoideus"),
("Soil insects", "various"),
("Solenopsis mealybug", "Phenacoccus solenopsis"),
("Sorghum midge", "Stenodiplosis sorghicola"),
("Sorghum head caterpillar", "Cryptoblabes adoceta"),
("Soybean aphid", "Aphis glycine"),
("Soybean leafminer", "Porphyrosela aglaozona"),
("Soybean looper", "Thysanoplusia orichalcea"),
("Soybean moth", "Aproaerema simplexella"),
("Spotted alfalfa aphid", "Therioaphis trifolii"),
("Spur-throated locust", "Austracris"),
("Strawberry spider mite", "Tetranychus lambi"),
("Stored grain pests", "various"),
("Sugarcane armyworm", "Leucania stenographa"),
("Sugarcane looper", "Mocis frugalis"),
("Swarming leaf beetle", "Rhyparidaspp."),
("Thrips", "various"),
("Thrips, Onion", "Thrips tabaci"),
("Thrips, Cotton seedling", "Thrips tabaci"),
("Thrips, Maize", "Frankliniella williamsi"),
("Thrips, Plague", "Thrips imaginis"),
("Thrips, tobacco", "Thrips tabaci"),
("Thrips, Tomato", "Frankliniella schultzei"),
("Thrips, Western flower", "Frankliniella orientalis"),
("Tobacco looper", "Chrysodeixis argentifera"),
("Tortrix", "Epiphyasa postvittana"),
("True wireworm", "Agrypnusspp."),
("Turnip aphid", "Lipaphis erysimi"),
("Two-spotted mite/spider mite", "Tetranychus urticae"),
("Vegetable leafhopper", "Austroasca viridigrisea"),
("Vegetable looper", "Chrysodeixis eriosoma"),
("Vegetable weevil", "Listroderes difficilis"),
("Weed web moth", "Achyra affinitalis"),
("Western flower thrip", "Frankliniella orientalis"),
("Wheat aphid", "Rhopalosiphum padi"),
("Whiteflies", "various"),
("Greenhouse whitefly", "Trialeurodes vaporariorum"),
("Silverleaf whitefly", "Bemisia tabacibiotype B and Australian native AN"),
("Silverleaf whitefly", "Bemisia tabacibiotype Q"),
("Whitegrub", "Heteronyxspp."),
("Wingless cockroaches", "Calolampraspp."),
("Wingless grasshopper", "Phaulacridium vittatum"),
("Wireworm, False", "PterohelaeusandGonocephalumspp."),
("Wireworm, True", "Agrypnusspp."),
("Yellow peach moth", "Conogethes punctiferalis"),
("Yellow-winged locust", "Gastrimargus musicus")